apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-eptp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-eptp
    app.kubernetes.io/part-of: test-app-dyng
  name: test-component-eptp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-eptp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-eptp
    spec:
      containers:
      - image: quay.io/susdas/test-images:c85915f2f3f6478eacfd49b0cbd5d59d
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
